'use strict';

export const TYPES = {
    REQUEST_TOKEN: 'REQUEST_TOKEN',
    LOAD_OPPSTAGES: 'LOAD_OPPSTAGES',
    LOAD_USERS: 'LOAD_USERS',
    LOAD_OPPS: 'LOAD_OPPS',
    CHANGE_APPSTATE: 'CHANGE_APPSTATE'
}
