'use strict';

export const TYPES = {
    REQUEST_TOKEN: 'REQUEST_TOKEN',

    LOAD_OPPSTAGES: 'LOAD_OPPSTAGES',
    LOAD_USERS: 'LOAD_USERS',
    LOAD_OPPS: 'LOAD_OPPS',

    UPDATE_OPP: 'UPDATE_OPP',

    LOAD_STAGEFILTERS: 'LOAD_STAGEFILTERS',
    UPDATE_STAGEFILTERS: 'UPDATE_STAGEFILTERS',

    CHANGE_APPSTATE: 'CHANGE_APPSTATE'
}
